# Workflow for deploying .NET Core app to Azure with enhanced EF Core migration handling

name: Build and deploy ASP.Net Core app to Azure Web App - prismon-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build project
        run: dotnet build --configuration Release --no-restore
      
      - name: Run tests
        run: dotnet test --configuration Release --no-build --no-restore
      
      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish --no-restore
      
      # Enhanced EF Core migration step with better error handling and detailed output
      - name: Debug project structure for migrations
        run: |
          echo "Current directory: $(pwd)"
          echo "Project files:"
          find . -name "*.csproj" | sort
          echo "Context files:"
          find . -name "*Context.cs" | sort
      
      - name: Apply EF Core migrations with verbose output
        run: |
          # First list migrations to verify connection and context
          echo "Listing migrations:"
          dotnet ef migrations list --project Prismon.Api.csproj --context PrismonDbContext --verbose
          
          # Then apply migrations with detailed output
          echo "Applying migrations:"
          dotnet ef database update --project Prismon.Api.csproj --context PrismonDbContext --verbose
        env:
          SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prismon-api'
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.PRISMON_DEPLOY_SECRET }}

          