# Workflow for deploying .NET Core app to Azure with EF migrations and Redis cache flush

name: Build and deploy ASP.Net Core app to Azure Web App - prismon-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build project
        run: dotnet build --configuration Release --no-restore
      
      - name: Run tests
        run: dotnet test --configuration Release --no-build --no-restore
      
      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish --no-restore
      
      - name: Apply EF Core migrations
        run: dotnet ef database update --project Prismon.Api.csproj --context PrismonDbContext
        env:
          SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Flush Azure Cache for Redis
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az redis flush --name prismon-redis --resource-group prismon-rg --confirm
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prismon-api'
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_437651DAC0C04682AFED1ABB2738DC8F }}
